from enum import Enum

class ProductStatus(Enum):
    AVAILABLE = "AVAILABLE"
    SOLD = "SOLD"
    PAUSED = "PAUSED"
    CREATED = "CREATED"
    DELETED = "DELETED"

class ProductCategory(Enum):
    REAL_ESTATE = "REAL_ESTATE"
    CARS_AND_PARTS = "CARS_AND_PARTS"
    HOME_DECORATION_AND_UTENSILS = "HOME_DECORATION_AND_UTENSILS"
    CONSTRUCTION_MATERIALS_AND_GARDEN = "CONSTRUCTION_MATERIALS_AND_GARDEN"
    ELECTRONICS_AND_CELL_PHONES = "ELECTRONICS_AND_CELL_PHONES"
    FASHION_AND_BEAUTY = "FASHION_AND_BEAUTY"
    SPORTS_AND_LEISURE = "SPORTS_AND_LEISURE"
    AGRICULTURE_AND_INDUSTRY = "AGRICULTURE_AND_INDUSTRY"
    SERVICES = "SERVICES"
    JOBS = "JOBS"
    BABY_ITEMS = "BABY_ITEMS"
    PETS = "PETS"
    MUSIC_AND_HOBBIES = "MUSIC_AND_HOBBIES"
    DEFALUT = "DEFAULT"